name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          echo "Deploying to Vercel..."
          vercel --token ${VERCEL_TOKEN} --prod --yes \
            -e DATABASE_URL=${DATABASE_URL} \
            -e POSTGRES_URL=${POSTGRES_URL} \
            -e SUPABASE_URL=${SUPABASE_URL} \
            -e SUPABASE_KEY=${SUPABASE_KEY} \
            -e JWT_SECRET=${JWT_SECRET} \
            -e SMTP_HOST=${SMTP_HOST} \
            -e SMTP_PORT=${SMTP_PORT} \
            -e SMTP_USER=${SMTP_USER} \
            -e SMTP_PASS=${SMTP_PASS}
