name: Deploy to Vercel
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Debug Environment
        run: |
          echo "Debugging environment variables (without revealing values)..."
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then echo "VERCEL_TOKEN is set"; else echo "VERCEL_TOKEN is not set"; fi
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then echo "VERCEL_ORG_ID is set"; else echo "VERCEL_ORG_ID is not set"; fi
          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then echo "VERCEL_PROJECT_ID is set"; else echo "VERCEL_PROJECT_ID is not set"; fi
          echo "Working directory contents:"
          ls -la
      
      # Utilizzo dell'azione ufficiale Vercel
      - name: Deploy to Vercel
        uses: vercel/actions/cli@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
